# Generated by Django 2.2.5 on 2021-01-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('about', models.TextField(default='-')),
                ('fb', models.CharField(max_length=40)),
                ('tw', models.CharField(max_length=40)),
                ('yt', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=40)),
                ('link', models.CharField(max_length=40)),
                ('set_name', models.CharField(max_length=40)),
            ],
        ),
    ]
