# Generated by Django 2.2.5 on 2021-01-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210116_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='pin',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='main',
            name='vi',
            field=models.CharField(max_length=40),
        ),
    ]
